/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as core from "./core";
export type { core };
import type * as governance from "./governance";
export type { governance };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MockERC20 } from "./MockERC20";
