/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEscrowManager,
  IEscrowManagerInterface,
} from "../../../../contracts/governance/DisputeResolution.sol/IEscrowManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "buyerWins",
        type: "bool",
      },
    ],
    name: "resolveDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEscrowManager__factory {
  static readonly abi = _abi;
  static createInterface(): IEscrowManagerInterface {
    return new Interface(_abi) as IEscrowManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEscrowManager {
    return new Contract(address, _abi, runner) as unknown as IEscrowManager;
  }
}
